name: Use Reusable Workflow

on: [push, pull_request]

jobs:
  call-reusable:
    uses: keerthi-umss/Workflow-Hands-on/.github/workflows/reuse_1.yaml@main  
    with:
      node-version: "18"
    secrets:
      token: ${{ secrets.NEW_TOKEN }}
