name: Caching Example

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ✅ Cache dependencies using a fixed key
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/my_project  # Directory to cache
          key: myproject-${{ runner.os }}-v1
          restore-keys: |
            myproject-${{ runner.os }}-

      - name: Install Dependencies
        run: |
          mkdir -p ~/.cache/my_project
          echo "Installing dependencies..." > ~/.cache/my_project/dependencies.log

      - name: Build Project
        run: echo "Building project..." > build.log

      # ✅ Upload build logs as an artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

  test:
    needs: build  # ✅ Wait for the build job to complete
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-log

      - name: Run Tests
        run: cat build.log
