name: Reusable Workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  greet-reusable:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, ${{ inputs.username }}!"
