name: Webhook Demo
 
on:
  push:
    branches:
      - main

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook
        run: |
          curl -X POST "https://webhook.site/159bf395-1d37-46e1-af11-6bf0fb467158" \
          -H "Content-Type: application/json" \
          -d '{"message": "A new push was made to the main branch!"}'
